### ISSUE TITLE
Not working in rhythmbox 3.4.2

### ISSUE THREAD

**Issue by jejo86** [fossfreedom/remember-the-rhythm#7]
This plugin does not seem to work in rhythmbox 3.4.2. The plugin is loaded and can be configured, but it does not continue playing the last song.

The last commit was 4 years ago. Are you still working on this?

**Comment by fossfreedom** [comment]
Odd. Does sound like a bug. Pull requests welcome._

**Comment by jejo86** [comment]
I'll see if I can contribute anything.

Reading the docs I found out how to debug your plugin. I get the following error, which is thrown around every second, while a song is being played:
```
Traceback (most recent call last):
  File "/usr/lib/rhythmbox/plugins/remember-the-rhythm/remember-the-rhythm.py", line 233, in elapsed_changed
    if self._scenario != 4:
AttributeError: 'RememberTheRhythm' object has no attribute '_scenario'
```

**Comment by fossfreedom** [comment]
Basically means the variable needs to be initialized before it is used.

**Comment by SimonDedman** [comment]
Similarly, I just upgraded to xubuntu 22.04 and while RTR remained installed, it no longer works. I reinstalled from source/git and then the ubuntu repository but no change. Rhythmbox v3.4.4; any suggestions Dave? Can I uninstall RTR, reboot, reinstall, and try again, in case that knocks it into life? Cheers!

**Comment by S377** [comment]
> I'll see if I can contribute anything.
> 
> Reading the docs I found out how to debug your plugin. I get the following error, which is thrown around every second, while a song is being played:
> 
> ```
> Traceback (most recent call last):
>   File "/usr/lib/rhythmbox/plugins/remember-the-rhythm/remember-the-rhythm.py", line 233, in elapsed_changed
>     if self._scenario != 4:
> AttributeError: 'RememberTheRhythm' object has no attribute '_scenario'
> ```

Hi,
I have exactly the same issue and log. Has a solution been found ?

FYI, I'm using Rhythmbox 3.4.4 on Ubuntu 22.04.2.

**Comment by SimonDedman** [comment]
> Can I uninstall RTR, reboot, reinstall, and try again, in case that knocks it into life?

This didn't work FWIW. Would be wonderful to have this working again.
